### PR TITLE
Restructure repository

### PR DESCRIPTION
**Pull request by p-galligan**
Moves scripts around to restructure repository into function areas.

### CODE REVIEW

**Comment by p-galligan** [comment]
@helrond I've looked through all of the scripts here, and every one that interacts with AS already uses ASnake. I only deleted a single test script.

Most others are just moving files around in directories, making CSVs, or performing other admin/cleanup tasks.

**Comment by helrond** [comment]
The following scripts can be deleted:
- access/archivesSpaceCsvDigitization.py
- access/generateDigitizationSip.py
- access/generateGebodSip.py
- access/generateRfodSip.py
- access/microfilm-csv.py
- access/microfilm-sips.py
- access/premisCsvDigitization.py
- access/startTransfer.py
- digital_strategies/archivesSpaceCsvDigitalMedia.py

**Comment by helrond** [comment]
I'm thinking maybe adding some subdirectories within each area for systems would make things clearer. For example, in the digital_strategies directory, let's create a `cantaloupe` subdirectory and a `utils` subdirectory (and maybe others?). In the `processing` dir, the ArchivesSpace stuff can go in one directory and the Wiki stuff in another.

**Comment by a-berish** [comment]
Looks good to me! My selfish concern was if this affected the imaging scripts, which it doesn't because they have their own repo.

**Pull request merged**
